export const companies_info_data = [
  { name: "TechNova Solutions", industry: "IT Industry", location: "Bangalore, India", website: "www.technova.in" },
  { name: "GreenLeaf Organics", industry: "Agriculture", location: "Pune, India", website: "www.greenleaforganic.com" },
  { name: "UrbanEdge Constructions", industry: "Real Estate", location: "Hyderabad, India", website: "www.urbanedge.in" },
  { name: "MediCare Plus", industry: "Healthcare", location: "Chennai, India", website: "www.medicareplus.com" },
  { name: "BrightSpark Education", industry: "Education", location: "Delhi, India", website: "www.brightsparkedu.com" },
  { name: "FinVista Capital", industry: "Finance", location: "Mumbai, India", website: "www.finvista.in" },
  { name: "EcoWave Energy", industry: "Renewable Energy", location: "Ahmedabad, India", website: "www.ecowaveenergy.com" },
  { name: "AeroTech Dynamics", industry: "Aerospace", location: "Bangalore, India", website: "www.aerotechdynamics.in" },
  { name: "UrbanThreads Apparel", industry: "Fashion & Retail", location: "Surat, India", website: "www.urbanthreads.in" },
  { name: "AgriGrow Solutions", industry: "Agriculture", location: "Nagpur, India", website: "www.agrigrow.in" },
  { name: "BlueOrbit Technologies", industry: "IT Industry", location: "Noida, India", website: "www.blueorbittech.com" },
  { name: "SkyNet Communications", industry: "Telecom", location: "Kolkata, India", website: "www.skynetcom.in" },
  { name: "NextGen Motors", industry: "Automobile", location: "Pune, India", website: "www.nextgenmotors.in" },
  { name: "PureDrop Beverages", industry: "FMCG", location: "Indore, India", website: "www.puredrop.in" },
  { name: "DataVision Analytics", industry: "IT Industry", location: "Gurgaon, India", website: "www.datavisionanalytics.com" },
  { name: "HomeNest Interiors", industry: "Interior Design", location: "Hyderabad, India", website: "www.homenest.in" },
  { name: "SafeTrack Logistics", industry: "Transportation", location: "Mumbai, India", website: "www.safetracklogistics.com" },
  { name: "MediZen Pharma", industry: "Healthcare", location: "Chandigarh, India", website: "www.medizenpharma.in" },
  { name: "BrightPixel Studios", industry: "Media & Entertainment", location: "Chennai, India", website: "www.brightpixelstudios.in" },
  { name: "LearnQuest Academy", industry: "Education", location: "Bangalore, India", website: "www.learnquestacademy.in" },
  { name: "BuildRight Infra", industry: "Real Estate", location: "Delhi, India", website: "www.buildrightinfra.com" },
  { name: "VoltUp Electricals", industry: "Manufacturing", location: "Pune, India", website: "www.voltup.in" },
  { name: "CyberNest Solutions", industry: "IT Industry", location: "Hyderabad, India", website: "www.cybernest.in" },
  { name: "AquaPure Systems", industry: "Water Technology", location: "Cochin, India", website: "www.aquapuresystems.com" },
  { name: "EcoRide Mobility", industry: "Automobile", location: "Bangalore, India", website: "www.ecoridemobility.in" },
  { name: "FoodieCart Services", industry: "Food & Beverages", location: "Delhi, India", website: "www.foodiecart.in" },
  { name: "Insight Financials", industry: "Finance", location: "Mumbai, India", website: "www.insightfinancials.in" },
  { name: "BrightBuild Developers", industry: "Real Estate", location: "Ahmedabad, India", website: "www.brightbuild.in" },
  { name: "HealthSync Diagnostics", industry: "Healthcare", location: "Lucknow, India", website: "www.healthsync.in" },
  { name: "TechOrbit Labs", industry: "IT Industry", location: "Bangalore, India", website: "www.techorbitlabs.in" }
];
